#!/usr/bin/env python3
"""Check out-of-plane stresses (σ₃₃) in wrinkle region under tension.

Runs a single FE case and reports the stress components at the
wrinkle peak to verify that σ₃₃ is generated by the curved geometry.

The curved-beam effect: σ₃₃ = σ_applied · t / R
where R is the local radius of curvature of the wrinkle.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from wrinklefe.analysis import AnalysisConfig, WrinkleAnalysis
from wrinklefe.core.material import MaterialLibrary

MATERIAL_NAME = "T700_2510_Elhajjar2014"
PLY_THICKNESS = 0.152
N_PLIES = 16
LAM_THICKNESS = N_PLIES * PLY_THICKNESS
LAYUP = [0, 45, 90, -45, 0, 45, -45, 0, 0, -45, 45, 0, -45, 90, 45, 0]
K_LAMBDA = 19.9
LAMBDA_MIN = 8.2


def check_stresses(dt_ratio: float, loading: str = "tension"):
    """Run FE and report stress components at wrinkle peak."""
    amplitude = dt_ratio * LAM_THICKNESS
    wavelength = max(K_LAMBDA * amplitude, LAMBDA_MIN)
    width = 0.75 * wavelength
    domain_length = max(3.0 * wavelength, 10.0)

    mat = MaterialLibrary().get(MATERIAL_NAME)

    config = AnalysisConfig(
        amplitude=amplitude,
        wavelength=wavelength,
        width=width,
        morphology="graded",
        decay_floor=0.0,
        loading=loading,
        material=mat,
        angles=LAYUP,
        ply_thickness=PLY_THICKNESS,
        nx=20, ny=6, nz_per_ply=3,
        domain_length=domain_length,
        domain_width=10.0,
        applied_strain=0.01 if loading == "tension" else -0.01,
        solver="direct",
        verbose=False,
    )

    result = WrinkleAnalysis(config).run()

    print(f"\n  D/T = {dt_ratio:.3f}, Loading = {loading}")
    print(f"  Amplitude = {amplitude:.3f} mm, Wavelength = {wavelength:.1f} mm")
    print(f"  Max fiber angle = {np.degrees(result.max_angle_rad):.1f}°")
    print(f"  Mesh max angle = {np.degrees(result.mesh_max_angle_rad):.1f}°")

    # Get stress field from FieldResults
    fr = result.field_results
    if fr is not None and fr.stress_global is not None and fr.stress_global.size > 0:
        # stress_global has shape (n_elements, n_gauss, 6)
        # Average over Gauss points to get element-level stresses
        stresses = fr.stress_global.mean(axis=1)  # (n_elements, 6)
        # Convention: [σ₁₁, σ₂₂, σ₃₃, τ₂₃, τ₁₃, τ₁₂]

        print(f"\n  Stress field shape (raw): {fr.stress_global.shape}")
        print(f"  Stress field shape (elem avg): {stresses.shape}")
        print(f"\n  {'Component':>10s} {'Mean':>10s} {'Max':>10s} {'Min':>10s} {'|Max|':>10s}")
        print("  " + "-" * 50)
        labels = ["σ₁₁", "σ₂₂", "σ₃₃", "τ₂₃", "τ₁₃", "τ₁₂"]
        for i, label in enumerate(labels):
            col = stresses[:, i]
            print(f"  {label:>10s} {col.mean():>10.1f} {col.max():>10.1f} "
                  f"{col.min():>10.1f} {np.abs(col).max():>10.1f}")

        # Ratio of out-of-plane to in-plane
        s11_max = np.abs(stresses[:, 0]).max()
        s33_max = np.abs(stresses[:, 2]).max()
        t23_max = np.abs(stresses[:, 3]).max()
        t13_max = np.abs(stresses[:, 4]).max()
        if s11_max > 0:
            print(f"\n  σ₃₃/σ₁₁ ratio: {s33_max/s11_max:.3f} ({s33_max/s11_max*100:.1f}%)")
            print(f"  τ₂₃/σ₁₁ ratio: {t23_max/s11_max:.3f} ({t23_max/s11_max*100:.1f}%)")
            print(f"  τ₁₃/σ₁₁ ratio: {t13_max/s11_max:.3f} ({t13_max/s11_max*100:.1f}%)")
        else:
            print("\n  WARNING: σ₁₁ max is zero — cannot compute ratios")

        # Compare σ₃₃ to matrix strengths
        Yt = mat.Yt if mat.Yt else 49.0
        S23 = mat.S23 if hasattr(mat, 'S23') and mat.S23 else 50.0
        print(f"\n  σ₃₃_max = {s33_max:.2f} MPa")
        print(f"  σ₃₃_max / Yt = {s33_max/Yt:.3f}")
        print(f"  τ₂₃_max / S23 = {t23_max/S23:.3f}")

        # Also report interlaminar stresses at ply interfaces
        try:
            il_s33, il_t13, il_t23 = fr.interlaminar_stresses()
            if il_s33.size > 0:
                print(f"\n  Interlaminar stresses (ply interfaces):")
                print(f"    σ₃₃ max = {np.abs(il_s33).max():.2f} MPa (interface avg)")
                print(f"    τ₁₃ max = {np.abs(il_t13).max():.2f} MPa")
                print(f"    τ₂₃ max = {np.abs(il_t23).max():.2f} MPa")
        except Exception as e:
            print(f"\n  (interlaminar stress extraction failed: {e})")
    else:
        print("\n  WARNING: No stress field available in results")

    # LaRC05 retention
    if result.retention_factors and "larc05" in result.retention_factors:
        print(f"\n  LaRC05 retention = {result.retention_factors['larc05']:.3f}")

    # Failure detail
    if hasattr(result, 'failure_detail') and result.failure_detail:
        print(f"\n  Failure detail: {result.failure_detail}")

    return result


def main():
    print("=" * 70)
    print("  Out-of-Plane Stress Check in Wrinkle Region")
    print("=" * 70)

    # Test a few D/T ratios
    for dt in [0.010, 0.050, 0.100, 0.200]:
        check_stresses(dt, "tension")

    print("\n  --- Compression comparison ---")
    for dt in [0.050, 0.100]:
        check_stresses(dt, "compression")

    print("\n" + "=" * 70)


if __name__ == "__main__":
    main()
